Algoritmo "q11"
//
//
// Descrição   : compreendido entre 20 e 90 ou não.
// Autor(a)    : ingrid
// Data atual  : 03/04/2024
Var
   // Seção de Declarações das variáveis
   num: real

Inicio
   // inserir dados
   escreva("digite um numero: ")
   leia(num)
   //condiçao
   se (num>20) e (num<90) entao
   //resposta
      escreval("o numero digitado esta entre 20 e 90")
   senao
      escreval ("o numero digitado nao esta entre 20 e 90")
      
      fimse

Fimalgoritmo