Algoritmo "atv5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : rafael
// Descrição   : Faça um programa que receba um nome e a idade do usuário.
// Autor(a)    : ingrid
// Data atual  : 01/04/2024
Var
// Seção de Declarações das variáveis 
  idade: real
  nome: caractere

Inicio
// inserir o nome do usuario
escreva("digite seu nome: ")
leia(nome)
// inserir idade
escreva("digite sua idade: ")
leia(idade)


Fimalgoritmo