Algoritmo "ativ 9"
//
//
// Descrição   : Faça um algoritmo que receba o número, calcule e mostre se ele é par ou impar
// Autor(a)    : ingrid
// Data atual  : 01/04/2024
Var
   // Seção de Declarações das variáveis
   num: inteiro

Inicio
   // inserir numero
   escreva("digite um numero: ")
   leia(num)
   //par ou impar
   se num % 2 = 0 entao
      escreva("o numero ", num, "é par.")
   senao
      escreva("o numero ", num, "é impar.")
Fimalgoritmo
fimse